### PR TITLE
Linux binaries for v2.0.0

### PR DESCRIPTION
**Pull request by am11**
**Updated (12.02.2015)**

*  Linux: Adds binary for v2.0.0. 
  * node.js v0.10 ia32.
  * node.js v0.10 x64.
  * node.js v0.12 ia32.
  * node.js v0.12 x64.
  * io.js v0.12 ia32.
  * io.js v0.12 x64.
 
//cc https://github.com/sass/node-sass/issues/655

### CODE REVIEW

**Comment by xzyfer** [comment]
This is a month old, is this still relevant, should it be regenerated?

**Comment by am11** [comment]
Yes I will repush to this PR.

**Comment by am11** [comment]
@xzyfer, I have added the binaries covering six entries of matrix.

If you have access to a Linux system (preferably Ubuntu), can you test them randomly before we merge? My system doesn't have enough memory to run another VM. :)

**Comment by am11** [comment]
Confirmed! The binaries are working on Ubuntu v12.0.4.

**Pull request merged**
