### PR TITLE
Add warning about using this repo

### PR DESCRIPTION
**Pull request by nschonni**
@xzyfer noticed someone recommending curling from this repo on SO, so I thought I'd add a warning

### CODE REVIEW

**Comment by xzyfer** [comment]
It's also worth noting these binaries very out of date. We should probably kill off this repo now. Thoughts @am11 @saper?

**Comment by nschonni** [comment]
I think old versions were pointing at this (maybe), so that would be my only trouble with killing it entirely

**Comment by xzyfer** [comment]
Yeah you're right. It'd be good to get stats on version fragmentation. Any version that references this repo hasn't been supported for a long time now.

**Comment by nschonni** [comment]
Maybe just nuke all the bindings in the current branch too

**Comment by xzyfer** [comment]
I think we can get some data out of npm around installation numbers. 

We should use `npm deprecate` to make npm produce a deprecation warning on installation of older versions. 

- Removing the binaries from master also makes sense.
- Noting that only binaries  <= 3.8.0 are available here

**Comment by nschonni** [comment]
:100: Makes sense to add the deprecate on the old packages

**Comment by am11** [comment]
Agree on issuing the `npm deprecate` warning for older version. 👍 

At some point, the idea was to also treat this repo as binaries backup store, in case one of us accidentally deletes the binary from the release assets. If there is not even that usage anymore, then nuking the repo makes sense.

Probably, would make sense to do a commit removing everything, keeping the readme around for a while noting "we are pulling the plug on this repo, update to newer version of node-sass". Then wait for a couple of weeks before R.I.P'ing the repo.

**Comment by saper** [comment]
I think we could keep offering this repo for the very purpose of having a local binary cache. It needs some work to be useful for this purpose (various releases would need to be unpacked into version directories) but maybe with an unpack script and some hopefully minimal node-sass installer changes it could be become quite useful and let us close this long-standing request with node-sass

**Comment by TheJaredWilcurt** [comment]
What has changed with Node-Sass that this is now deprecated?

From my understanding when you `npm install node-sass` it will check your OS/Arch/Node versions and download the correct binding from this repo.

I'm running Node-Sass from inside of NW.js, which has different version of Node than what I have installed globally. So I need to manually copy the correct version into the `node_modules/node-sass/vendor/OS-Arch-NodeV` folder.

I've been using this repo as a source for my copy of the bindings so I can do automated builds for different platforms.

Relevant files files from my project:

* https://github.com/scout-app/scout-app/tree/master/scout-files/_assets/node-sass_v3.8.0
* https://github.com/scout-app/scout-app/blob/master/scout-files/_scripts/libsass-fix.js

**Comment by nschonni** [comment]
> From my understanding when you npm install node-sass it will check your OS/Arch/Node versions and download the correct binding from this repo.

I couldn't find the exact version, but it's been using the GH releases downloads since at least 3.2.0

**Pull request merged**
