### PR TITLE
Add darwin x64 binaries for 3.0.0-preview

### PR DESCRIPTION
**Pull request by xzyfer**
This PR adds Darwin x64 binaries for 3.0.0-preview. Includes 
- node 0.10.36
- node 0.12.0
- iojs 1.0
- iojs 1.1->1.5.1

### CODE REVIEW

**Comment by am11** [comment]
Perfect! Should we just delete existing directories?

**Comment by xzyfer** [comment]
I can't think of a reason to keep them.

**Comment by am11** [comment]
Yup version control rocks! :wink:

**Comment by xzyfer** [comment]
Updated the compat table

**Comment by am11** [comment]
:+1: I will also make Linux and Windows binaries for both varied modules of iojs.

**Comment by am11** [comment]
Feel free to merge it in whenever it is ready.

**Pull request merged**
