### PR TITLE
Binary for FreeBSD 10.x(amd64) node 0.12

### PR DESCRIPTION
**Pull request by saper**

### CODE REVIEW

**Comment by saper** [comment]
New style name for this file will be `freebsd-x64-3.28.73`

Maybe it could be beneficial to differentiate major FreeBSD versions, since FreeBSD up to 9 (inclusive) use GCC and `libstdc++` runtime and FreeBSD 10 and later use `clang` and LLVM C++ libraries. But this version should be good for now.

**Comment by am11** [comment]
@saper, glad to know that it worked out for you. :sunny: 

For contribution, you will need to build the binary from the cloned node-sass repo:

```bash
# after forking node-sass repo on github
cd /tmp
git clone https://github.com/saper/node-sass recursive
cd node-sass
git submodule update --init --recursive
npm install
node scripts/build -f
```

You will find that `vendor/` directory will have a subdirectory with new naming convention (like you mentioned).

Also, to solve the runtime issue, the best approach is always to build with the minimum version of libc. See the long conversation here: https://github.com/sass/node-sass/issues/517. So the oldest version of FreeBSD, which supports GCC v4.6+ will be the best to obtain maximum coverage.

Note that this is just one piece of the puzzle, we need to build against node.js v0.12 x64, v0.10 ia32/x64, io.js v1.4 ia32/x64 as well (which is possible using [nvm](https://github.com/creationix/nvm) and io.js) for fast version switching and given 32-bit toolkit is installed). :)

**Comment by saper** [comment]
Thanks! I think you mean `git clone --recursive` :)

My goal was to provide something usable *now* for those running 2.0.1 

Well FreeBSD does not really have the libc problem discussed in sass/node-sass#517 because libc is much more stable. We also have compatibility packages to to use the older libc if necessary but this does not seem to be the issue for anything than quite ancient systems.

The real issue which is coming soon to Linux is the C++ library. I would propose to introduce a check  for that in sass/node-sass#733 

So I have rebuilt the binding according to your instructions:

https://gist.github.com/saper/d571c97391506c9334de

it actually produced identical binary as submitted and the tests seem to pass as well.

**Comment by am11** [comment]
Yeah missed `--`. My bad. :)

> My goal was to provide something usable *now* for those running 2.0.1 

It is not possible, because we make a tagged release and once the release is build there is no way to inject files in it. Related discussion is going here: https://github.com/sass/node-sass/issues/712.

I think we should hold off until node-sass is ready.

**Comment by saper** [comment]
Ah, I see. No problem. I have now automated builds running for gcc-based FreeBSD 8 (amd64 and i386) and for clang-based FreeBSD 10. Will try to support iojs as well. Closing for now, thanks!

**Pull request closed without merging**
