### PR TITLE
Windows binaries for v2.0.0

### PR DESCRIPTION
**Pull request by am11**
**Updated (12.02.2015)**

*  Windows: Adds binary for v2.0.0. 
  * node.js v0.10 ia32.
  * node.js v0.10 x64.
  * node.js v0.12 ia32.
  * node.js v0.12 x64.
  * io.js v0.12 ia32.
  * io.js v0.12 x64.
 
//cc https://github.com/sass/node-sass/issues/655

### CODE REVIEW

**Comment by am11** [comment]
@andrew, would you please add the Mac binary for v2?   :smiley_cat:

**Comment by andrew** [comment]
@am11 I've built the binary but when running the tests I get the following:

```
andrews-mbp-2:node-sass andrew$ npm test

> node-sass@2.0.0-beta pretest /Users/andrew/code/node-sass
> jshint bin lib test


> node-sass@2.0.0-beta test /Users/andrew/code/node-sass
> mocha test



  api
    .render(options)
      ✓ should compile sass to css with file 
      ✓ should compile sass to css with data 
      ✓ should compile sass to css using indented syntax 
      ✓ should throw error status 1 for bad input 
      ✓ should compile with include paths 
      ✓ should compile with image path 
      ✓ should throw error with non-string image path 
      ✓ should render with --precision option 
      ✓ should contain all included files in stats when data is passed 
    .render(importer)
Abort trap: 6
```

I can take a look at it this evening, can you remind me of the steps to debug it?

**Comment by am11** [comment]
@andrew, this is basically a known issue: https://github.com/sass/node-sass/issues/586. I made some fixes for Linux and Win but couldn't figure out what is going wroyng on OSX by the logs posted by OP.

To reproduce, run the following in node-sass repo's root:

```javascript
require("./").render({
    data: "@import \"non-existing-file\"; \n.test {\ncolor: #000;\n}",
    outputStyle: 'compressed',
    success: function(result) {
        console.log(result);
    },
    error: function(error) {
        console.log(error);
    },
    importer: function(url, prev, done) {
        done({contents: 'div { color: #000; }'});
    }
});
```

I think the minimal code to reproduce would be:

```javascript
require("./").render({
    data: "@import \"non-existing-file\"; \n.test {\ncolor: #000;\n}",
    importer: function(url, prev, done) {
        done({contents: 'div { color: #000; }'});
    }
});
```

However, changing render to renderSync would probably pass.

To debug, I used the following approaches:

* `gdb /usr/bin/node node_modules/.bin/mocha test`
  * this will attach the debugger while running the tests.
* `strace -Ff -tt /usr/bin/node node_modules/.bin/mocha test 2>&1 | tee /tmp/strace-node-sass.log`
  * provided you have strace installed 
  * This will generate a verbose log file: /tmp/strace-node-sass.log. [Example](https://gist.github.com/am11/a8327f77401133e2368e)
* `G_SLICE=always-malloc G_DEBUG=gc-friendly  valgrind -v --tool=memcheck --leak-check=full --show-reachable=yes --num-callers=40 --log-file=/tmp/valgrind.log $(which node) node_modules/.bin/mocha test`
  * provided you have valgrind installed 
  * this will generate the log file `/tmp/valgrind.log`. This is mostly used to detect memory leaks and other memory related issues. [Example](https://gist.github.com/am11/1898f979f737e9d69072)

I think it is happening somewhere [here](https://github.com/sass/node-sass/blob/fc1d4e6e72cbf0079c51d5c238ea4b8da0d0bff7/src/binding.cpp#L88-L89), where the next function to be executed is [`dispatched_async_uv_callback`](https://github.com/sass/node-sass/blob/master/src/binding.cpp#L53-L72).

**Comment by andrew** [comment]
I'm totally swamped with freelance work at the moment, not going to have any time to debug this at the moment, sorry.

**Comment by am11** [comment]
Its totally alright. I know the feeling. I think this importer might not be fixed for OSX in the next release. But we can wait a little longer, since @xzyfer may look into it soon. :)

**Comment by xzyfer** [comment]
This is a month old, is this still relevant, should it be regenerated?

**Comment by am11** [comment]
Once Linux binaries are ready, I will rebuild for Windows and r.

**Pull request merged**
