### PR TITLE
Add Windows binaries for 3.3.0

### PR DESCRIPTION
**Pull request by xzyfer**

### CODE REVIEW

**Comment by am11** [comment]
We can now pull these from appveyor artifacts. :)

**Comment by xzyfer** [comment]
Old habbits lol

On 8/24/15, Adeel Mujahid <notifications@github.com> wrote:
> We can now pull these from appveyor artifacts. :)
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sass/node-sass-binaries/pull/82#issuecomment-134130567


-- 
Regards,
Michael

**Comment by am11** [comment]
Lol, I mean we can still push the downloaded artifact it to this repo, to keep the record straight. But we don't need to build those ourselves. ;)

**Comment by xzyfer** [comment]
Yeah totally got you. Just forgot about the artefact thing :)

**Comment by xzyfer** [comment]
Do we have it set up for travis/osx builds yet?

**Comment by am11** [comment]
For Travis, we will need to configure S3 bucket. Probably we need to find someone to sponsor it as @andrew once mentioned. Once that is done, and we are able to configure Docker for Linux binaries (build using CentOS 5), we can automate it completely. The only stopper is S3 bucket as of this moment.

Mind map / TODOs after S3 bucket is arranged:

* OSX binaries will be uploaded as is, since there are no cross-compile issues there (we can also make it so that it push when the new tag is pushed, already happening in node-sass-middleware repo).
* For Linux binaries; once the build succeed (and again optionally "new tag" condition is satisfied), we can run the Docker job and push the resultant binary from the Docker job. (Note to self): Point to ponder is we need to somehow pass parameter (the current node version of job) to Docker job so each instance of matrix build two binaries (x86 and ia64 variants) for the selected node.js version.
* FreeBSD Docker can be configured later just like Linux. What I have not figure out yet is how to cross compile (x86 on ia64) in FreeBSD. But with my experiments compiling other libraries in FreeBSD VM, I think it will be quite doable. We may also be able to configure a "composite" Dockerfile using https://github.com/docker/compose for Linux and FreeBSD which will run per job matrix and result in four binaries for each OS+architecutre and given node version.

When / If all of the above worked out, we will push the appveyor artifact to the same instance of S3 bucket and change our install script to download binaries from S3 directly. :)

Later other OSes/architectures can join the pool.

**Comment by xzyfer** [comment]
>For Travis, we will need to configure S3 bucket.

That's cool. Since we'll ideally only push binaries on tags I can use my personal s3.

>Probably we need to find someone to sponsor it 

I also know some people who might be keen to help out here.

>For Linux binaries ...  we can run the Docker job and push the resultant binary from the Docker job

_posting for reference_

Until recently running docker in travis ci was not possible due to security concerns. @am11 realised this restriction [has been lifted](http://docs.travis-ci.com/user/docker/).

>FreeBSD Docker can be configured later just like Linux

This would be amazing!

>What I have not figure out yet is how to cross compile (x86 on ia64) in FreeBSD

@saper will likely have some thoughts here.

>When / If all of the above worked out, we will push the appveyor artifact to the same instance of S3 bucket 

:+1: 

>change our install script to download binaries from S3 directly

My initial thoughts are not to do this. IMHO downloading the binaries to the GH releases is the optimal solution. The explicit versioning is great! For the foreseeable future I'm perfectly happy manual steps of:

- downloading the binaries
- creating the node-sass-binaries PR
- attaching binaries to the node-sass GH release

**Comment by saper** [comment]
On Mon, 24 Aug 2015, Michael Mifsud wrote:

> >FreeBSD Docker can be configured later just like Linux

> >What I have not figure out yet is how to cross compile (x86 on ia64) in FreeBSD
> 
> @saper will likely have some thoughts here.

kFreeBSD Debian project might have been doing this. Docker does not currently work with FreeBSD,
so you would need to set up a cross-compiling environment and keep it current.

**Comment by xzyfer** [comment]
>Docker does not currently work with FreeBSD

@am11 linked me to these - 

https://wiki.freebsd.org/Docker
https://github.com/rocker-org/rocker/blob/56cb59cc262e9d2c02f9e11cfacab65f0b659c5f/.travis.yml#L10-L24

Admittedly I have not read them myself, but you might have more context for what this means to us.

**Comment by saper** [comment]
On Mon, 24 Aug 2015, Michael Mifsud wrote:

> https://github.com/rocker-org/rocker/blob/56cb59cc262e9d2c02f9e11cfacab65f0b659c5f/.travis.yml#L10-L24

This is how to make Travis CI run docker, I think...

> >Docker does not currently work with FreeBSD
> 
> @am11 linked me to these - 
> 
> https://wiki.freebsd.org/Docker

Long way to go, but maybe somebody should give it a try...

**Comment by am11** [comment]
I have empty slot in the coming weekend. I will start by parameterizing [current Dockerfile](https://gist.github.com/am11/1529b2458b1a1f4bdba8), so it build one pair of binaries for the given node.js version. On this note, should we add that Dockerfile in this repo under `scripts/` or `tools/`?

**Comment by xzyfer** [comment]
>I will start by parameterizing current Dockerfile

Here is the one I use now for reference - https://gist.github.com/xzyfer/f5623546cb73b601b9b8

>should we add that Dockerfile in this repo 

Emphatically yes. Infact we'll need this when we build [Linux binaries in Travis](http://docs.travis-ci.com/user/docker/#Building-a-Docker-Image-from-a-Dockerfile).

**Comment by am11** [comment]
I like your version better (as there is no 12.37 hack for node-v0.10.37-linux-x86.tar.gz)! :smile:
Lets add that one here then.

**Pull request merged**
