### PR TITLE
FreeBSD 10.x binaries for node-sass 3.0.0-beta4

### PR DESCRIPTION
**Pull request by saper**
Those binaries will not work with GCC-based
FreeBSD 8.x and 9.x releases.

### CODE REVIEW

**Comment by am11** [comment]
Thanks @saper! :+1: :tada: 

Are those signature files mandatory? If not we can probably remove them since we are not trying to become a real libsass' package manager for FreeBSD. :smile_cat:

**Comment by saper** [comment]
No, they are not mandatory. I also have real FreeBSD packages but they need a bit more work... I think it's just a good practice and other should be signed, too.

**Comment by am11** [comment]
This definitely seems like a good practice.
However, for the scope of this PR, you can remove and rebase the signature files. 
After that we can discuss this matter separately on how to incorporate signature generation in our build system (probably in `.gyp` file or post compilation) for various platforms, so the future contributors don't have to figure out on their own how to generate these, hence an inconvenience/confusion.

**Comment by saper** [comment]
Well, I prefer small steps towards the goal instead of waiting for The Big Implementation Someday.


## How to sign binaries

I have signed those files using those Bourne shell commands:

````
for i in freebsd*node
do
  gpg --detach-sign -a $i
done
````

## Signature verification

To verify, one has download my key first:

    gpg --search-key 50A02077

and then you can do

    for i in *.asc; do echo Checking $i; gpg --verify $i; done

The output should be:

````
Checking freebsd-ia32-11_binding.node.asc
gpg: Signature made Thu Apr  2 23:26:27 2015 CEST using RSA key ID 50A02077
gpg: Good signature from "Marcin Cieslak <saper@saper.info>"
Checking freebsd-ia32-14_binding.node.asc
gpg: Signature made Thu Apr  2 23:26:32 2015 CEST using RSA key ID 50A02077
gpg: Good signature from "Marcin Cieslak <saper@saper.info>"
Checking freebsd-ia32-42_binding.node.asc
gpg: Signature made Thu Apr  2 23:26:35 2015 CEST using RSA key ID 50A02077
gpg: Good signature from "Marcin Cieslak <saper@saper.info>"
Checking freebsd-ia32-43_binding.node.asc
gpg: Signature made Thu Apr  2 23:26:39 2015 CEST using RSA key ID 50A02077
gpg: Good signature from "Marcin Cieslak <saper@saper.info>"
Checking freebsd-x64-11_binding.node.asc
gpg: Signature made Thu Apr  2 23:26:42 2015 CEST using RSA key ID 50A02077
gpg: Good signature from "Marcin Cieslak <saper@saper.info>"
Checking freebsd-x64-14_binding.node.asc
gpg: Signature made Thu Apr  2 23:26:45 2015 CEST using RSA key ID 50A02077
gpg: Good signature from "Marcin Cieslak <saper@saper.info>"
Checking freebsd-x64-42_binding.node.asc
gpg: Signature made Thu Apr  2 23:26:49 2015 CEST using RSA key ID 50A02077
gpg: Good signature from "Marcin Cieslak <saper@saper.info>"
Checking freebsd-x64-43_binding.node.asc
gpg: Signature made Thu Apr  2 23:26:52 2015 CEST using RSA key ID 50A02077
gpg: Good signature from "Marcin Cieslak <saper@saper.info>"
````

But I made the signature as a separate commit so feel free to cherry-pick if you don't want them.

**Comment by am11** [comment]
> Well, I prefer small steps towards the goal

Lets first discuss with others what the "goal" rally is and why we want to do things differently compared to what other module repo folks are doing. I am not opposing your ideas, but my only concern is if everyone start going tangent in PRs, this with compromise consistency.


 > feel free to cherry-pick if you don't want them.

You can rebase out that commit so this PR gets merged right away.

**Comment by am11** [comment]
Thanks! :tada:

**Comment by saper** [comment]
:dancer:

**Pull request merged**
