### PR TITLE
Add 2.0.0 Darwin x64 node 0.10 binary

### PR DESCRIPTION
**Pull request by xzyfer**
This PR adds the 2.0.0 Darwin x64 node 0.10 binary. 

Binary generated from https://github.com/sass/node-sass/commit/9c3accb784d94d5fce1a2bc9b73486c0605ee80b. 

/cc https://github.com/sass/node-sass/issues/655

### CODE REVIEW

**Comment by am11** [comment]
:heavy_check_mark: :tada:

**Comment by xzyfer** [comment]
Does merging this break current 2.0.0-beta installs?

**Comment by am11** [comment]
Nops. The URLs are tied to release (which has the same version as node-sass release), so we are in safe zone! :)

For instance: https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.0-beta/win32-x64/binding.node.

So node-sass and node-sass-binaries releases will always be in sync.

**Comment by xzyfer** [comment]
Ah great! I was curious how we were going to time the merges. Do you think it's worth tagging 2.0.0 stable then? (no publishing) so we have a known point to build assets from.

**Comment by am11** [comment]
Yes we can tag these as 2.0.0. I do not have any idea how to do that at pre-publish state. :smile:

**Pull request merged**
