### PR TITLE
Windows: Adds binaries for v3.0.0

### PR DESCRIPTION
**Pull request by am11**
@xzyfer, here we go! :sunglasses:

### CODE REVIEW

**Comment by am11** [comment]
Before merging this, should we lock down v3.0.0-beta.7 tag in this repo?

**Comment by xzyfer** [comment]
Hmm I'm going to assume the 3.0.0-beta.6 Windows and Linux binaries work fine for 3.0.0-beta.7 since we've had no issues. Will tag 3.0.0-beta.7 now.

**Comment by xzyfer** [comment]
Done https://github.com/sass/node-sass-binaries/releases/tag/v3.0.0-beta.7

**Comment by am11** [comment]
Great thanks! :+1: 
Looking forward for v3.0 stable. :sunglasses:

**Pull request merged**
