### PR TITLE
Added FreeBSD-x64-node-0.12 binary

### PR DESCRIPTION
**Pull request by mariusvw**
Added FreeBSD 64bit support, compiled on FreeBSD 10.1

### CODE REVIEW

**Comment by am11** [comment]
Please compile the binary with v3 tag code.

```bash
git clone https://github.com/sass/node-sass
cd node-sass
git checkout tags/v3.0.0-pre
node scripts/build -f
```

You will find the `vendor/freebsd-x64xxx/binding.node`. Rename `binding.node` to `freebsd-x64xxx_binding.node` and only commit that file (without directory). See the example in current master: https://github.com/sass/node-sass-binaries/.

**Comment by mariusvw** [comment]
Added the new binary according to the name you described.

Maybe nice for the readme to add the commands required to build the binaries?

**Comment by am11** [comment]
Thanks!

I have updated the node-sass README: https://github.com/sass/node-sass/commit/735b718dd50740e61254c4ae2d11ab4c7f203f64.

**Comment by saper** [comment]
Thanks @mariusvw - 

1. can you post some more details about your environment (`uname -a`) and the clang version used? 2. What was the command line you have given to the build commands (i.e. how did you select the compiler?)
3. Can you post your `npm test` results to gist.github.com?

**Comment by mariusvw** [comment]
Sure:
# uname -a
FreeBSD stuff.bsdpowered.net 10.1-RELEASE-p6 FreeBSD 10.1-RELEASE-p6 #0: Tue Feb 24 19:00:21 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

# clang --version
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512

I have g++ symlinked to clang by default

# Commands used to compile:
git clone https://github.com/sass/node-sass
cd node-sass
git checkout tags/v3.0.0-pre
git submodule update --init --recursive
npm install
node scripts/build -f

# GIST
https://gist.github.com/mariusvw/5c7947f729c7053bb0b0

**Pull request merged**
